# ----------- Motion detector parameters --------
# General.
#evaluate: true # Set by launch file
#visualize: true
#num_threads: 1  # uses hardware concurrency if left empty.
queue_size: 10
shutdown_after: 10  # num evaluations.
  
# Preprocessing.
preprocessing:
  min_range: &min_range 1  # m
  max_range: &max_range 20  # m

# Ever-Free Integration.
ever_free_integrator:
  counter_to_reset: 150 # Observations to un-free an ever-free voxel [frames]
  temporal_buffer: 2   # To compensate sparsity [frames].
  burn_in_period: 5   # Burn in before becoming ever-free [frames].
  tsdf_occupancy_threshold: 0.3 # 1.5 voxel sizes.
  neighbor_connectivity: 18
  
# Clustering.
clustering:
  min_cluster_size: 20
  max_cluster_size: 20000
  neighbor_connectivity: 6
  
# Tracking.
tracking:
  use_tracking: true
  min_track_duration: 2 # frames
  max_tracking_distance: 1  # m
  
# Evaluation.
evaluation:
  min_range: *min_range  # m
  max_range: *max_range  # m
  evaluate_point_level: true
  evaluate_cluster_level: true
  evaluate_object_level: true
  evaluate_ranges: true
  evaluate_range_at_level: cluster # point, cluster, object
  
# Visualization.
visualization:
  static_point_color: [0,0,0,1]
  dynamic_point_color: [1,0,0.5,1]
  static_point_scale: 0.03
  dynamic_point_scale: 0.08
  sensor_scale: 0.5
  color_clusters: true
  color_wheel_num_colors: 20
  
# Voxblox parameters.
voxblox:
  # SDF.
  tsdf_voxel_size: 0.2
  truncation_distance: 0.4
  tsdf_voxels_per_side: 16
  max_weight: 1000
  
  # Integration.
  method: projective
  sensor_horizontal_resolution: 2048
  sensor_vertical_resolution: 64
  sensor_vertical_field_of_view_degrees: 33.22222
  min_ray_length_m: *min_range
  max_ray_length_m: *max_range
  use_const_weight: true
  verbose: false
