# ----------- Motion detector parameters --------
# General.
#evaluate: true # Set by launch file
#visualize: true
# num_threads: 8  # uses hardware concurrency if left empty.
queue_size: 100
shutdown_after: 3

# Preprocessing.
preprocessing:
  min_range: &min_range 0.5  # m
  max_range: &max_range 20  # m
  evaluation_range: 20  # m

# Clustering.
clustering:
  min_cluster_size: 20
  max_cluster_size: 20000
  neighbor_connectivity: 6

# Ever-Free Integration.
ever_free_integrator:
  counter_to_reset: 120
  temporal_buffer: 2   # To compensate sparsity.
  burn_in_period: 5
  tsdf_occupancy_threshold: 0.3 # 1.5 voxel sizes.
  neighbor_connectivity: 18
  
# Evaluation.
evaluation:
  min_range: *min_range  # m
  max_range: *max_range  # m
  evaluate_point_level: true
  evaluate_cluster_level: true
  evaluate_object_level: true
  
# Visualization
visualization:
  static_point_color: [0,0,0,1]
  dynamic_point_color: [1,0,0.5,1]
  static_point_scale: 0.05
  dynamic_point_scale: 0.1
  color_clusters: true
  color_wheel_num_colors: 20
  

# Voxblox parameters
voxblox:
  tsdf_voxel_size: 0.2
  tsdf_voxels_per_side: 16
  voxel_carving_enabled: true
  color_mode: lambert
  truncation_distance: 0.45
  use_tf_transforms: true

  tsdf_max_distance_m: 0.45
  tsdf_default_distance_m: 0.45
  update_mesh_every_n_sec: 0.0
  min_time_between_msgs_sec: 0.01

  min_ray_length_m: *min_range
  max_ray_length_m: *max_range
  
  sensor_horizontal_resolution: 2048
  sensor_vertical_resolution: 64
  sensor_vertical_field_of_view_degrees: 33.22222

  allow_clear: true
  verbose: false
  publish_tsdf_map: false
  publish_pointlouds: false
  output_mesh_as_pointcloud: false
  publish_tsdf_info: false
  publish_slices: true
  slice_level: 0
  publish_pointclouds_on_update: false
  max_weight: 1000
  method: projective
  use_const_weight: true
  integrator_threads: 8
